### ISSUE TITLE
Operators not working in SalesLoft

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-salesloft#16]
**Repro Steps:**
1. Run crank cog:steps automatoninc/salesloft
2. Select the Check a field on a SalesLoft person
3. Type in the email address
4. Then type the field name
5. Choose any operator except for be
6. Enter the expected value then press enter.

**Repro Steps 2:**
1. Run the yml file
```yml
scenario: SalesLoft Person Test with operator
description: This tests the operator when creating a salesloft person

steps:
- step: create or update a salesloft person
  data:
    person:
        email_address: customfieldssalesloft@thisisjust.atomatest.com
        NicksTest123: This is Custom
- step: the email_address field on salesloft person customfieldssalesloft@thisisjust.atomatest.com should contain atomatest.com
```

**Actual Result:**
![image](https://user-images.githubusercontent.com/54615569/70994980-58b70380-210a-11ea-98aa-fa69fb6334b0.png)
![image](https://user-images.githubusercontent.com/54615569/70994986-5fde1180-210a-11ea-8ec2-c76e8ea8a53a.png)
![image](https://user-images.githubusercontent.com/54615569/70995000-6b313d00-210a-11ea-9e84-d407abb90d47.png)

**Expected Result:**
Operators should work as expected
