### ISSUE TITLE
Operator is not working in custom fields

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-salesloft#17]
Repro Steps:
1. Run the yml file
```yml
scenario: SalesLoft Person Test with operator
description: This tests the operator when creating a salesloft person

steps:
- step: create or update a salesloft person
  data:
    person:
        email_address: custom@thisisjust.atomatest.com
        NicksTest123: This is Custom
- step: the email_address field on salesloft person custom@thisisjust.atomatest.com should be custom@thisisjust.atomatest.com
- step: the NicksTest123 field on salesloft person custom@thisisjust.atomatest.com should contain custom
- step: delete the custom@thisisjust.atomatest.com salesloft person
```
**Actual Result:**
![image](https://user-images.githubusercontent.com/54615569/70995819-68cfe280-210c-11ea-8db1-076eb5edcc95.png)

**Expected Result:**
Note: Custom field is passing when using be or not using any operators
![image](https://user-images.githubusercontent.com/54615569/70995784-53f34f00-210c-11ea-9ee8-709bf8e93b70.png)
User shall be able to use the operators on custom fields.
