### ISSUE TITLE
Person check field regex is too restrictive

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-salesloft#29]
## Repro Steps
1. Run the following scenario:
```yml
scenario: Custom Person Field with Spaces
description: Proves that custom fields whose API names contain spaces can be checked.

tokens:
  test.email: test-more-custom@thisisjust.atomatest.com

steps:
- step: When I create or update a salesloft person
  data:
    person:
      email_address: '{{test.email}}'
      Sales Lead Owner: abc
- step: Then the Sales Lead Owner field on salesloft person test-more-custom@thisisjust.atomatest.com should be abc
- step: Then delete the {{test.email}} salesloft person
```

**Expected**: The scenario run should pass.

**Actual**: The scenario doesn't run at all, producing the following error message:

```
Error running scenario:
  Error: Missing step definition for "Then the Sales Lead Owner field on salesloft
  person test-more-custom@thisisjust.atomatest.com should be abc"
```

--- 

The regex capture group for `field` should allow spaces.
